Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : algoritmos
// Autor(a)    : Isabela Santiago
// Data atual  : 05/12/2024
Var
// Seção de Declarações das variáveis 
 valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um valor: ")
leia(valor)
se valor >= 0 entao
escreva("O valor é POSITIVO!")
senao
escreva("O valor é NEGATIVO!")
fimse

Fimalgoritmo