Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Atividade
// Autor(a)    : Isabela Santiago
// Data atual  : 04/12/2024
Var
// Seção de Declarações das variáveis 
numero, resultado:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva ("digite o numero: ")
Leia (numero)

resultado <- numero - 1
Escreva ("O antecessor desse numero é: ", resultado)
Fimalgoritmo