Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Atividaade algoritmos
// Autor(a)    : Isabela Santiago
// Data atual  : 05/12/2024
Var
// Seção de Declarações das variáveis
F,C: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite a temperatura em Fahrenheit: ")
  leia(F)
C <- (F - 32) * 5 / 9

escreval("A temperatura em Celsius é: ", C:0:2)



Fimalgoritmo