Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : FERNANDA NALON
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
resultado: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita

resultado <- resultado + 1
escreval (resultado)
ate resultado = 10

Fimalgoritmo