Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : FERNANDA NALON
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 

cont: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 10

repita
escreval(cont)
cont <- cont - 1
ate cont < 1

Fimalgoritmo