Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernando Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
 numero: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero <- 2

enquanto numero < 500 faca

escreval(numero)

numero <- numero + 2

fimenquanto

Fimalgoritmo