Algoritmo "PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernando Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
para i de 10 ate 1 passo -1 faca
      escreval(i)
   fimpara
Fimalgoritmo