Algoritmo "PARA"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernando Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
i, xx: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um valor: ")
   leia(xx)
   para i de 1 ate xx faca
      escreval(i)
   fimpara
Fimalgoritmo