Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Isabela Santiago
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis
contador, resultado: inteiro
inicio
contador:= 1
enquanto (contador <= 10) faca
resultado:= 8 * contador
escreval("8 x ", contador, " = ", resultado)
contador:= contador + 1
fimenquanto
Fimalgoritmo